[versions]
keycloak = "26.6.4"
jnats = "2.21.1"
jbossLogging = "3.6.3.Final"
junit = "6.1.1"
shadow = "9.4.3"

[libraries]
keycloakCore = { module = "org.keycloak:keycloak-core", version.ref = "keycloak" }
keycloakServerSpi = { module = "org.keycloak:keycloak-server-spi", version.ref = "keycloak" }
keycloakServerSpiPrivate = { module = "org.keycloak:keycloak-server-spi-private", version.ref = "keycloak" }
jbossLogging = { module = "org.jboss.logging:jboss-logging", version.ref = "jbossLogging" }
jnats = { module = "io.nats:jnats", version.ref = "jnats" }
junitJupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junitPlatformLauncher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit" }

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
